### ISSUE TITLE
Hi! Question about incorporating DUBStepR into Seurat sctransform integration workflow.

### ISSUE THREAD

**Issue by martinfalck** [prabhakarlab/DUBStepR#1]
Hi!

I really enjoyed reading the paper and I think your approach to the clustering problem is a good one. 

I think most people who integrate many samples do that using Seurat's SCTtransform: ([https://satijalab.org/seurat/articles/integration_introduction.html]. 

You used an example in the vignette of a single dataset and recommended using DUBStepR with log-normalized data. My question is what is your workflow recommendation when it comes to integrating multiple samples and using DUBStepR? 

Some questions I can think of: 
Can one run DUBStepR directly on the SCT assay data-slot (SCT@data), even though you recommend it to be used for log-normalized data (RNA@data)?
If not, we must run the integration vignette (the one based on log-normalization) first, but then my question is if you can explain, or show an example, of when DUBStepR is incorportated in this process.

Thanks for developing this cool tool!

**Comment by bbbranjan** [comment]
Hi @martinfalck, thank you for trying DUBStepR, and we're glad you liked our approach! 

When integrating multiple samples using DUBStepR, as you suggested, we recommend following the conceptual strategy proposed by the Satija lab ([https://satijalab.org/seurat/articles/integration_introduction.html](https://satijalab.org/seurat/articles/integration_introduction.html)). Basically, we recommend performing feature selection on each normalized sample individually, and using the union set of the features selected as the integration features. 

Yes, you can run DUBStepR with the SCT data slot. One of our collaborators has generated good results by doing so (unpublished), and theoretically we think DUBStepR should work well with the SCT data slot. Thus, if you would like to integrate datasets normalized using SCTransform ([https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1)), you can run DUBStepR on the data slot of the SCT assay of each sample after performing SCTransform, and use the union set of the features selected by DUBStepR as the integration features.

Please let us know if you need any further explanation, or if you have any other questions about DUBStepR :)

**Comment by martinfalck** [comment]
Thanks for a nice answer @bbbranjan!

**Comment by martinfalck** [comment]
@bbbranjan, in the sake of being important, I just wanted to double-check its the union of genes that are to be used, not the intersection. It was just confusing me a little since when looking for anchors between two datasets should it not be genes expressed in both and not genes only seen in only one. Its worth asking an extra time :)

Edit: I guess the FindIntegrationAnchors() does that anyway. So might have been a dumb question.

**Comment by bbbranjan** [comment]
@martinfalck yes this is an important question. Ideally we integrate samples of similar nature (same tissue/organ/organism), so we rarely run into the issue that a gene selected as an interesting feature in one dataset is not even expressed in the other one. In saying that, we should be mindful that this could potentially be an issue while integrating highly distinct samples.

The main reason we recommend using the union rather than the intersection is because we want to include cell types, and any kind of biologically relevant variation, that may be present in only one of the samples (which would be discarded by the intersection).

**Comment by martinfalck** [comment]
Ah I see. It makes sense since we would need to place the unrelated/different (across the samples) cells somewhere when integrating, not just the similar ones. 

Anyway thanks again!

**Comment by SHADJIA** [comment]
Hello,

I'm also interested in your issue. I performed DUBStepR on individual datasets (data slot). I took the unique features from each list and set as anchor.features for the command `FindIntegrationAnchors`. And then perfomed the steps as indicated in Seurat vignette. Am I doing correctly?

Regards,
Sha

**Comment by bbbranjan** [comment]
@SHADJIA, thanks for your question! Yes, using the union set of unique features from each individual dataset is a good strategy.

**Comment by SHADJIA** [comment]
@bbbranjan Thanks for your quick reply
