### ISSUE TITLE
extent DUBStepR to miRNA data

### ISSUE THREAD

**Issue by WhitePredator** [prabhakarlab/DUBStepR#2]
Dear Bobby, can this package be implemented on miRNA or protein data? 
when I do that with TCGA miRNA data, it returns an error to me:
"Error in sorted_corr[3, ] : incorrect number of dimensions"

**Comment by bbbranjan** [comment]
Dear @WhitePredator , thanks for raising this issue! I'm definitely interested in extending DUBStepR to miRNA data, but haven't had the chance to formally test it yet. Could you share the dimensions of the input data matrix and the parameter settings you are using while running DUBStepR?

**Comment by WhitePredator** [comment]
I use default parameters and TCGA miRNA data is about 743*sample number.  Sample numbers may range from 10 to 1000

> Dear @WhitePredator , thanks for raising this issue! I'm definitely interested in extending DUBStepR to miRNA data, but haven't had the chance to formally test it yet. Could you share the dimensions of the input data matrix and the parameter settings you are using while running DUBStepR?

**Comment by bbbranjan** [comment]
Sorry for the delay, @WhitePredator . There may be an issue in the data filtering, resulting in a 1-dimensional vector being input into the `getCorrelationRange()` function. Could you source the _getFilteredData.R_ file and load the _sysdata_ from this repository into your workspace, and then run `getFilteredData(<your-dataset>)` ? If the output is a 1-dimensional vector, you could try decreasing the _min.cells_ threshold, or even setting it to 0.

**Comment by bbbranjan** [comment]
Another possible issue might be the formatting of the rownames in the input dataset. Could you paste the output of `head(rownames(<your-dataset>))` below?
