### ISSUE TITLE
Customize panel genes for single cell experiment

### ISSUE THREAD

**Issue by SHADJIA** [prabhakarlab/DUBStepR#6]
Hello @bbbranjan,

I'm working in a project  to define minimum marker genes in order to customize a panel of genes to sequence for upcoming single cell experiments in my lab. 
Do you think it's possible to do so with the genes find with your package? Otherwise, what would you recommend to find minimum markers to sequence?

I thank you in advance for your advice.

Regards,
Sha

**Comment by bbbranjan** [comment]
Interesting question, @SHADJIA. I think there is a strong overlap between what you're trying to do and the intuition behind the stepwise regression approach in DUBStepR. If you follow the density index computation strategy and assess the marker gene panel at regular intervals, you should get the minimum marker panel that can cluster diverse cell types. The ordering of features in the DUBStepR output prioritizes diversity of marker genes, and so it should help answer your question. Hope this helps!

**Comment by SHADJIA** [comment]
Thanks a lot for your reply @bbbranjan !
I'll try to do so and come back to you if I have further issues.
